version: '3.7'

services:
  sensor:
    depends_on:
      - postgres
    build:
      context: .

    environment:
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_URL: $DB_URL
    restart: always
    ports:
     - 8083:8070

  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: 9876543219
      POSTGRES_USER: postgres
      POSTGRES_DB: sensor
    ports:
      - 5433:5432