create table if not exists sensor
(
    id   integer generated by default as identity
        primary key,
    name varchar(100) not null
        unique
);

create table if not exists measurement
(
    id         integer generated by default as identity
        constraint measurements_pkey
            primary key,
    value      double precision not null,
    raining    boolean          not null,
    sensor     varchar(100)     not null
        constraint measurements_sensor_fkey
            references sensor (name),
    created_at timestamp        not null
);
